[project]
name = "BERT Mojo Torchscript"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["pytorch", "conda-forge", "anaconda", "https://token:ldCjjn5d1qs8zK3S@conda.cloudsmith.io/modular/max-conda-test/"]
platforms = ["osx-arm64","linux-64"]

[dependencies]
python = ">=3.9,<3.13"
max = "==2024.8.1405"
pip = ">=24.0,<25"
pytorch = "~=2.2.2"
transformers = "*"
numpy = "<2.0.0"
