[project]
name = "BERT Mojo Torchscript"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "anaconda", "https://token:ldCjjn5d1qs8zK3S@conda.cloudsmith.io/modular/max-conda-test/"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]

[dependencies]
python = ">=3.9,<3.13"
max = "*"
pip = ">=24.0,<25"
